apiVersion: v1
kind: Service
metadata:
  name: kube-ops
  labels:
    chapter: services
spec:
  # ipFamilyPolicy: PreferDualStack
  # ipFamilies:
  # - IPv4
  # - IPv6
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30002
      targetPort: 8080
      protocol: TCP
  selector:
    chapter: services

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-lb
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 8080
  selector:
    chapter: services
